# Generated by Django 3.2 on 2021-11-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_rollno1', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_rollno2', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_rollno3', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_name4', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_rollno4', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_name5', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_rollno5', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_name6', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_rollno6', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_name7', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_rollno7', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_name8', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_rollno8', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_name9', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_rollno9', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_name10', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_rollno10', models.CharField(blank=True, max_length=100, null=True)),
                ('research', models.TextField(blank=True, null=True)),
                ('software', models.TextField(blank=True, null=True)),
                ('guide', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
