# Generated by Django 3.2 on 2021-12-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='stu_name10',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stu_name6',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stu_name7',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stu_name8',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stu_name9',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stu_rollno10',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stu_rollno6',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stu_rollno7',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stu_rollno8',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stu_rollno9',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=100, null=True)),
                ('rollno', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.ManyToManyField(to='collegeproject.Project')),
            ],
        ),
    ]
