# Generated by Django 3.2 on 2021-12-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeproject', '0003_auto_20211204_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
